default_platform(:ios)

platform :ios do
  desc "Push a new release to App Store Connect"
  lane :release do
    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      export_method: "app-store"
    )
    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true
    )
  end
end