name: Build and Deploy to App Store

on:
  push:
    branches: [ "main" ]

jobs:
    deploy:
        runs-on: macos-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies and build
              run: |
                  npm install
                  npm run build --if-present
                  npx cap sync ios

            - name: Build iOS Archive
              run: |
                  cd ios/App
                  xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -destination "generic/platform=iOS" -archivePath build/App.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
